//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizzBranding.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessPlan
    {
        public AccessPlan()
        {
            this.HomeBannerMappings = new HashSet<HomeBannerMapping>();
            this.Memberships = new HashSet<Membership>();
            this.NewsMappings = new HashSet<NewsMapping>();
        }
    
        public int AccessPlanId { get; set; }
        public string AccessPlanName { get; set; }
        public string Description { get; set; }
        public Nullable<int> MaxNoDeals { get; set; }
        public Nullable<int> ProdPerMonth { get; set; }
        public Nullable<int> UpdatesPerMonth { get; set; }
        public Nullable<decimal> AddPostCharge { get; set; }
        public Nullable<decimal> AddUpdCharge { get; set; }
        public Nullable<decimal> NewsCharge { get; set; }
        public int Validity { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<decimal> MembershipFee { get; set; }
        public string AccessPlanImage { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual ICollection<HomeBannerMapping> HomeBannerMappings { get; set; }
        public virtual ICollection<Membership> Memberships { get; set; }
        public virtual ICollection<NewsMapping> NewsMappings { get; set; }
    }
}
