//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizzBranding.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrator
    {
        public Administrator()
        {
            this.CoBrandings = new HashSet<CoBranding>();
            this.CorporateBrandings = new HashSet<CorporateBranding>();
            this.Franchises = new HashSet<Franchise>();
            this.GlobalBrandings = new HashSet<GlobalBranding>();
            this.InvestorPartnerings = new HashSet<InvestorPartnering>();
            this.NewsLetters = new HashSet<NewsLetter>();
            this.NewsLetters1 = new HashSet<NewsLetter>();
            this.News = new HashSet<News>();
            this.News1 = new HashSet<News>();
            this.Modules = new HashSet<Module>();
            this.Modules1 = new HashSet<Module>();
        }
    
        public int AdminId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public int RoleId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual ICollection<CoBranding> CoBrandings { get; set; }
        public virtual ICollection<CorporateBranding> CorporateBrandings { get; set; }
        public virtual ICollection<Franchise> Franchises { get; set; }
        public virtual ICollection<GlobalBranding> GlobalBrandings { get; set; }
        public virtual ICollection<InvestorPartnering> InvestorPartnerings { get; set; }
        public virtual ICollection<NewsLetter> NewsLetters { get; set; }
        public virtual ICollection<NewsLetter> NewsLetters1 { get; set; }
        public virtual ICollection<News> News { get; set; }
        public virtual ICollection<News> News1 { get; set; }
        public virtual ICollection<Module> Modules { get; set; }
        public virtual ICollection<Module> Modules1 { get; set; }
    }
}
