//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizzBranding.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BizzBrandingEntities : DbContext
    {
        public BizzBrandingEntities()
            : base("name=BizzBrandingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AccessPlan> AccessPlans { get; set; }
        public DbSet<Administrator> Administrators { get; set; }
        public DbSet<BusinessConnection> BusinessConnections { get; set; }
        public DbSet<BusinessEnquiry> BusinessEnquiries { get; set; }
        public DbSet<BusinessJob> BusinessJobs { get; set; }
        public DbSet<BusinessNew> BusinessNews { get; set; }
        public DbSet<BussinessUser> BussinessUsers { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<City> Cities { get; set; }
        public DbSet<CM> CMS { get; set; }
        public DbSet<CoBranding> CoBrandings { get; set; }
        public DbSet<CoBrandingImage> CoBrandingImages { get; set; }
        public DbSet<CorporateBranding> CorporateBrandings { get; set; }
        public DbSet<Country> Countries { get; set; }
        public DbSet<Currency> Currencies { get; set; }
        public DbSet<CustomerEnquiry> CustomerEnquiries { get; set; }
        public DbSet<EmailTemplate> EmailTemplates { get; set; }
        public DbSet<EmployeeBranding> EmployeeBrandings { get; set; }
        public DbSet<Franchise> Franchises { get; set; }
        public DbSet<GlobalBranding> GlobalBrandings { get; set; }
        public DbSet<HomeBanner> HomeBanners { get; set; }
        public DbSet<HomeBannerMapping> HomeBannerMappings { get; set; }
        public DbSet<Industry> Industries { get; set; }
        public DbSet<InvestorPartnering> InvestorPartnerings { get; set; }
        public DbSet<Membership> Memberships { get; set; }
        public DbSet<Message> Messages { get; set; }
        public DbSet<MessagesBlock> MessagesBlocks { get; set; }
        public DbSet<MessagesFile> MessagesFiles { get; set; }
        public DbSet<NewsLetter> NewsLetters { get; set; }
        public DbSet<NewsMapping> NewsMappings { get; set; }
        public DbSet<PaymentTransationDetail> PaymentTransationDetails { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<ProductImage> ProductImages { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<RoleAssignment> RoleAssignments { get; set; }
        public DbSet<SubCategory> SubCategories { get; set; }
        public DbSet<Subscribe> Subscribes { get; set; }
        public DbSet<TargetBranding> TargetBrandings { get; set; }
        public DbSet<TargetedImage> TargetedImages { get; set; }
        public DbSet<UserFriendMapping> UserFriendMappings { get; set; }
        public DbSet<UserIndustryMapping> UserIndustryMappings { get; set; }
        public DbSet<VisitorCount> VisitorCounts { get; set; }
        public DbSet<News> News { get; set; }
        public DbSet<Module> Modules { get; set; }
    }
}
