//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizzBranding.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessEnquiry
    {
        public int Id { get; set; }
        public Nullable<int> FromUserId { get; set; }
        public Nullable<int> ToUserId { get; set; }
        public string Subject { get; set; }
        public string EnquiryDetails { get; set; }
        public Nullable<System.DateTime> SentOn { get; set; }
        public Nullable<System.DateTime> ReadOn { get; set; }
        public bool IsSent { get; set; }
        public bool IsRead { get; set; }
        public bool IsDelete { get; set; }
    
        public virtual BussinessUser BussinessUser { get; set; }
        public virtual BussinessUser BussinessUser1 { get; set; }
    }
}
