//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizzBranding.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BussinessUser
    {
        public BussinessUser()
        {
            this.BusinessEnquiries = new HashSet<BusinessEnquiry>();
            this.BusinessEnquiries1 = new HashSet<BusinessEnquiry>();
            this.BusinessJobs = new HashSet<BusinessJob>();
            this.BusinessNews = new HashSet<BusinessNew>();
            this.BusinessNews1 = new HashSet<BusinessNew>();
            this.MessagesBlocks = new HashSet<MessagesBlock>();
            this.MessagesBlocks1 = new HashSet<MessagesBlock>();
            this.CoBrandings = new HashSet<CoBranding>();
            this.CoBrandings1 = new HashSet<CoBranding>();
            this.CorporateBrandings = new HashSet<CorporateBranding>();
            this.CustomerEnquiries = new HashSet<CustomerEnquiry>();
            this.EmployeeBrandings = new HashSet<EmployeeBranding>();
            this.Franchises = new HashSet<Franchise>();
            this.GlobalBrandings = new HashSet<GlobalBranding>();
            this.HomeBanners = new HashSet<HomeBanner>();
            this.HomeBannerMappings = new HashSet<HomeBannerMapping>();
            this.InvestorPartnerings = new HashSet<InvestorPartnering>();
            this.Memberships = new HashSet<Membership>();
            this.Messages = new HashSet<Message>();
            this.Messages1 = new HashSet<Message>();
            this.MessagesFiles = new HashSet<MessagesFile>();
            this.MessagesFiles1 = new HashSet<MessagesFile>();
            this.NewsMappings = new HashSet<NewsMapping>();
            this.PaymentTransationDetails = new HashSet<PaymentTransationDetail>();
            this.Products = new HashSet<Product>();
            this.TargetBrandings = new HashSet<TargetBranding>();
            this.UserIndustryMappings = new HashSet<UserIndustryMapping>();
            this.VisitorCounts = new HashSet<VisitorCount>();
            this.News = new HashSet<News>();
        }
    
        public int UserId { get; set; }
        public string BusinessName { get; set; }
        public string EmailId { get; set; }
        public string Password { get; set; }
        public string CompanyLogo { get; set; }
        public string CoRegNo { get; set; }
        public Nullable<int> IndustryId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> CityId { get; set; }
        public string CoAddress { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string ContactPerson { get; set; }
        public string Designation { get; set; }
        public string TradeEmaiIId { get; set; }
        public string BusinessDetails { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public bool IsActive { get; set; }
        public string GUId { get; set; }
        public bool IsGlobal { get; set; }
        public string BannerImage { get; set; }
        public Nullable<bool> IsRequested { get; set; }
        public Nullable<int> HitCounter { get; set; }
        public string URL { get; set; }
    
        public virtual ICollection<BusinessEnquiry> BusinessEnquiries { get; set; }
        public virtual ICollection<BusinessEnquiry> BusinessEnquiries1 { get; set; }
        public virtual ICollection<BusinessJob> BusinessJobs { get; set; }
        public virtual ICollection<BusinessNew> BusinessNews { get; set; }
        public virtual ICollection<BusinessNew> BusinessNews1 { get; set; }
        public virtual ICollection<MessagesBlock> MessagesBlocks { get; set; }
        public virtual ICollection<MessagesBlock> MessagesBlocks1 { get; set; }
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual Industry Industry { get; set; }
        public virtual ICollection<CoBranding> CoBrandings { get; set; }
        public virtual ICollection<CoBranding> CoBrandings1 { get; set; }
        public virtual ICollection<CorporateBranding> CorporateBrandings { get; set; }
        public virtual ICollection<CustomerEnquiry> CustomerEnquiries { get; set; }
        public virtual ICollection<EmployeeBranding> EmployeeBrandings { get; set; }
        public virtual ICollection<Franchise> Franchises { get; set; }
        public virtual ICollection<GlobalBranding> GlobalBrandings { get; set; }
        public virtual ICollection<HomeBanner> HomeBanners { get; set; }
        public virtual ICollection<HomeBannerMapping> HomeBannerMappings { get; set; }
        public virtual ICollection<InvestorPartnering> InvestorPartnerings { get; set; }
        public virtual ICollection<Membership> Memberships { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
        public virtual ICollection<Message> Messages1 { get; set; }
        public virtual ICollection<MessagesFile> MessagesFiles { get; set; }
        public virtual ICollection<MessagesFile> MessagesFiles1 { get; set; }
        public virtual ICollection<NewsMapping> NewsMappings { get; set; }
        public virtual ICollection<PaymentTransationDetail> PaymentTransationDetails { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<TargetBranding> TargetBrandings { get; set; }
        public virtual ICollection<UserIndustryMapping> UserIndustryMappings { get; set; }
        public virtual ICollection<VisitorCount> VisitorCounts { get; set; }
        public virtual ICollection<News> News { get; set; }
    }
}
