//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizzBranding.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.BussinessUsers = new HashSet<BussinessUser>();
            this.EmployeeBrandings = new HashSet<EmployeeBranding>();
            this.TargetBrandings = new HashSet<TargetBranding>();
        }
    
        public int CityId { get; set; }
        public string CityName { get; set; }
        public Nullable<int> CountryId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<BussinessUser> BussinessUsers { get; set; }
        public virtual Country Country { get; set; }
        public virtual ICollection<EmployeeBranding> EmployeeBrandings { get; set; }
        public virtual ICollection<TargetBranding> TargetBrandings { get; set; }
    }
}
