//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizzBranding.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoBrandingImage
    {
        public int Id { get; set; }
        public Nullable<int> CoBrandingId { get; set; }
        public string CoBrandingImage1 { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public bool IsActive { get; set; }
    
        public virtual CoBranding CoBranding { get; set; }
    }
}
