//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizzBranding.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerEnquiry
    {
        public int ContactId { get; set; }
        public string Name { get; set; }
        public string EmailId { get; set; }
        public string Phone { get; set; }
        public string Subject { get; set; }
        public string Enquiry { get; set; }
        public Nullable<int> LoginUserId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual BussinessUser BussinessUser { get; set; }
    }
}
