//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizzBranding.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeBranding
    {
        public int EmpBrandingId { get; set; }
        public Nullable<int> EmployerId { get; set; }
        public string EmpName { get; set; }
        public string EmpImage { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> No_Months { get; set; }
        public Nullable<int> IndustryId { get; set; }
        public Nullable<int> CityId { get; set; }
    
        public virtual BussinessUser BussinessUser { get; set; }
        public virtual City City { get; set; }
        public virtual Industry Industry { get; set; }
    }
}
