//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizzBranding.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GlobalBranding
    {
        public int GlobalBrandingId { get; set; }
        public Nullable<int> BusinessUserId { get; set; }
        public string GlobalBrandingDetails { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> No_Months { get; set; }
        public Nullable<System.DateTime> ExpiresOn { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
    
        public virtual Administrator Administrator { get; set; }
        public virtual BussinessUser BussinessUser { get; set; }
    }
}
