//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizzBranding.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Industry
    {
        public Industry()
        {
            this.BussinessUsers = new HashSet<BussinessUser>();
            this.EmployeeBrandings = new HashSet<EmployeeBranding>();
            this.TargetBrandings = new HashSet<TargetBranding>();
            this.UserIndustryMappings = new HashSet<UserIndustryMapping>();
        }
    
        public int IndustryId { get; set; }
        public string IndustryName { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<BussinessUser> BussinessUsers { get; set; }
        public virtual ICollection<EmployeeBranding> EmployeeBrandings { get; set; }
        public virtual ICollection<TargetBranding> TargetBrandings { get; set; }
        public virtual ICollection<UserIndustryMapping> UserIndustryMappings { get; set; }
    }
}
