//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizzBranding.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentTransationDetail
    {
        public int PaymentTransationId { get; set; }
        public string TransationId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string PaymentReturnId { get; set; }
        public Nullable<bool> TransationStatus { get; set; }
        public Nullable<int> UserId { get; set; }
        public string MessageFromGateway { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual BussinessUser BussinessUser { get; set; }
    }
}
