//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizzBranding.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TargetBranding
    {
        public TargetBranding()
        {
            this.TargetedImages = new HashSet<TargetedImage>();
        }
    
        public int TargetBrandingId { get; set; }
        public Nullable<int> IndustryId { get; set; }
        public Nullable<int> CityId { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> No_Months { get; set; }
        public Nullable<int> CreatedUserId { get; set; }
        public string BusinessName { get; set; }
        public string URL { get; set; }
        public Nullable<System.DateTime> ExpiresOn { get; set; }
    
        public virtual BussinessUser BussinessUser { get; set; }
        public virtual City City { get; set; }
        public virtual Industry Industry { get; set; }
        public virtual ICollection<TargetedImage> TargetedImages { get; set; }
    }
}
